### ISSUE TITLE
cookie提交显示格式错误

### ISSUE THREAD

**Issue by forEN13** [QooLianyi/PaimonsNotebook#3]
自动设置也无法加入账号

**Comment by QooLianyi** [comment]
自动设置如果无反应,麻烦在app打开的网页中退出登录,然后再登录。
cookie的格式现在是account_mid_v2,cookie_token_v2,ltoken_v2。

**Comment by forEN13** [comment]
cookie v2的获取方式是什么

**Comment by QooLianyi** [comment]
刚才发布了一个新版本(1.3.17),请使用新版本再尝试自动获取。cookiev2你可以在米游社的网站中获取，

**Comment by QooLianyi** [comment]
刚才发布了一个新版本(1.3.17),请使用新版本再尝试自动获取。cookiev2你可以在米游社的网站中获取，或者使用本软件通过cookie导出功能获取。
