### ISSUE TITLE
无法正常获取cookies

### ISSUE THREAD

**Issue by amokiel** [QooLianyi/PaimonsNotebook#4]
登录之后获取不了cookies，一直在米游社网页版的画面，可以修复一下。顺便问下什么时候可以更新呢，或者可以考虑先发布测试版。开发者辛苦了。

**Comment by QooLianyi** [comment]
当前正式版(1.3.18)无法获取Cookies是已知问题，该问题已在开发中的1.4版本解决；当前1.4版本已经完成账号的登录、多账号管理等功能，但由于本人近几个月学业较为繁重，所以暂时停止了新版本的开发，预计在未来的数月内恢复开发。先行测试版可能会在以后的更新计划中出现。

**Comment by amokiel** [comment]
> 当前正式版(1.3.18)无法获取Cookies是已知问题，该问题已在开发中的1.4版本解决；当前1.4版本已经完成账号的登录、多账号管理等功能，但由于本人近几个月学业较为繁重，所以暂时停止了新版本的开发，预计在未来的数月内恢复开发。先行测试版可能会在以后的更新计划中出现。

辛苦了！由衷希望可以考虑尽快发布先行测试版，这是个人感觉移动端体验最好的工具。祝开发者学业顺利，前程似锦！

**Comment by QooLianyi** [comment]
> 辛苦了！由衷希望可以考虑尽快发布先行测试版，这是个人感觉移动端体验最好的工具。祝开发者学业顺利，前程似锦！
>
感谢对本项目的支持，此Issues会保持开启，直到下次发布新版本时关闭。

**Comment by QooLianyi** [comment]
项目发布了一个预览版本，欢迎小伙伴进行体验。由于新版本已更新，此issue关闭。
