### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by Matthew-y** [QooLianyi/PaimonsNotebook#5]
祈愿记录的角色、武器图片无法显示，角色、武器资料的图片无法显示

**Comment by QooLianyi** [comment]
感谢小伙伴的反馈，最新版本(1.4.4)修复了此问题，小伙伴可以通过以下链接获取最新版本的安装包与查看更新日志：
https://github.com/QooLianyi/PaimonsNotebook/releases/tag/2023.12.7
最后感谢小伙伴对派蒙笔记本的支持

问题已解决，关闭此Issues
