### ISSUE TITLE
扫码不能登录了，而且奇怪的是识别二维码提示是否使用以下账号登录绝区零？

### ISSUE THREAD

**Issue by haliuhei** [QooLianyi/PaimonsNotebook#7]
如题游戏已到4.7版本，程序为当前最新，米游社为2.71.1

**Comment by QooLianyi** [comment]
感谢小伙伴的反馈，扫码登录功能异常的问题已经在下个版本修复。下个版本当前正在进行最后的功能测试，预计在最近几天就会发布。
关于二维码为什么显示的是绝区零，程序开发时使用的是绝区零的游戏id进行token获取，后续开发版本完毕，正式版打包时将修改回原神游戏id的操作遗漏了。起初是可以正常登录的，后续接口返回内容更改，导致现版本无法登录。

**Comment by haliuhei** [comment]
> 感谢小伙伴的反馈，扫码登录功能异常的问题已经在下个版本修复。下个版本当前正在进行最后的功能测试，预计在最近几天就会发布。 关于二维码为什么显示的是绝区零，程序开发时使用的是绝区零的游戏id进行token获取，后续开发版本完毕，正式版打包时将修改回原神游戏id的操作遗漏了。起初是可以正常登录的，后续接口返回内容更改，导致现版本无法登录。

感谢大佬，回复很迅速！静等更新。

**Comment by QooLianyi** [comment]
新版本已经更新，此issue描述的问题已解决。
可通过本项目release或访问以下链接获取新版本的安装包：
https://github.com/QooLianyi/PaimonsNotebook/releases/tag/1.6.0-9

一段时间后将关闭此issue
